// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"XdRs_Puzzle","status":false,"description":"拼图。","parameters":{"RandomBlankBlock":"ON","cpVal":"5","titleWord":"智力拼图","stepWord":"步数:","cmd1":"继续游戏","cmd2":"完整图片","cmd3":"退出游戏","titleColor":"0,200,200","stepColor":"255,180,0","anmId":"48"}},
{"name":"DK_MV_Plugins_Compatibility","status":true,"description":"v.1.0.6 Compatibility of RPG Maker MV plugins with RPG Maker MZ.","parameters":{}},
{"name":"MessageTextSound","status":true,"description":"v1.00 - 为事件的“显示文字”动作添加音效。","parameters":{"Text Sound Interval":"5","Text Sound Name":"Cursor1","Text Sound Volume":"20","Text Sound Pitch":"50","Text Sound Pan":"0"}}
];
